using Microsoft.Extensions.Localization;
using OrchardCore.Localization;

namespace OrchardCore.Workflows.Services;

/// <summary>
/// The client strings of the workflow designer (group <c>workflows-designer</c>).
/// </summary>
public sealed class WorkflowsDesignerJSLocalizer : IJSLocalizer
{
    /// <summary>
    /// The localization group the designer requests.
    /// </summary>
    public const string Group = "workflows-designer";

    internal readonly IStringLocalizer S;

    public WorkflowsDesignerJSLocalizer(IStringLocalizer<WorkflowsDesignerJSLocalizer> stringLocalizer)
    {
        S = stringLocalizer;
    }

    public IDictionary<string, string> GetLocalizations(string group)
    {
        if (!string.Equals(group, Group, StringComparison.OrdinalIgnoreCase))
        {
            return null;
        }

        return new Dictionary<string, string>
        {
            // Shell.
            { "WorkflowsList", S["Workflows"].Value },
            { "Loading", S["Loading the workflow…"].Value },
            { "LoadFailed", S["The workflow couldn't be loaded. Reload the page to try again."].Value },
            { "History", S["History"].Value },
            { "Undo", S["Undo"].Value },
            { "Redo", S["Redo"].Value },
            { "UndoShortcut", S["Undo (Ctrl+Z)"].Value },
            { "RedoShortcut", S["Redo (Ctrl+Y)"].Value },
            { "Toolbox", S["Toolbox"].Value },
            { "Close", S["Close"].Value },
            { "Cancel", S["Cancel"].Value },

            // Toolbox.
            { "SearchActivities", S["Search activities"].Value },
            { "ActivityKind", S["Kind of activities"].Value },
            { "All", S["All"].Value },
            { "Events", S["Events"].Value },
            { "Tasks", S["Tasks"].Value },
            { "LoadingActivities", S["Loading the activities…"].Value },
            { "LibraryLoadFailed", S["The activities couldn't be loaded."].Value },
            { "NoActivitiesFound", S["No activities match the search."].Value },
            { "AddActivity", S["Add {0}"].Value },
            { "AddActivityFailed", S["The activity couldn't be added. Reload the page and try again."].Value },

            // Workflow and activity panels.
            { "ActivityTab", S["Activity"].Value },
            { "ActivityTabHint", S["Edit the selected activity. Changes are saved as you make them."].Value },
            { "ActivityTabHintReadOnly", S["The details of the selected activity."].Value },
            { "WorkflowTabHint", S["The settings of this workflow: its name, whether it is enabled, and how its instances run."].Value },
            { "IssuesTabHint", S["Problems found in this workflow. Errors must be fixed before publishing; select one to go to its activity."].Value },
            { "Activities", S["Activities"].Value },
            { "ActivitiesHint", S["Drag an activity to the canvas, or click it to add it."].Value },
            { "ExpandToolbox", S["Show the activities"].Value },
            { "CollapseToolbox", S["Hide the activities"].Value },
            { "WorkflowTab", S["Workflow"].Value },
            { "VariablesTab", S["Variables"].Value },
            { "VariablesTabHint", S["The variables of this workflow, with their types and default values. Read them with variable(\"name\") in JavaScript or {{ Workflow.Variables.name }} in Liquid."].Value },
            { "VariablesTabHintReadOnly", S["The variables of this workflow, and the values this instance has."].Value },
            { "NoVariables", S["This workflow has no variables."].Value },
            { "VariableName", S["Name"].Value },
            { "VariableType", S["Type"].Value },
            { "VariableDefault", S["Default value"].Value },
            { "VariableValue", S["Value"].Value },
            { "VariableDescription", S["Description"].Value },
            { "AvailableData", S["Available data"].Value },
            { "AvailableDataHint", S["The data this activity can use. Click an expression to insert it where the cursor was in the settings, or to copy it."].Value },
            { "ActivitySettings", S["Settings"].Value },
            { "AvailableFrom", S["From {0}"].Value },
            { "AvailableWorkflow", S["Workflow"].Value },
            { "AvailableThisActivity", S["This activity"].Value },
            { "AvailableInputs", S["Inputs"].Value },
            { "InputHint", S["Passed by the workflow that runs this one, or by what starts it."].Value },
            { "AvailableGlobal", S["Global"].Value },
            { "AvailableFunctions", S["Functions"].Value },
            { "AvailableFilters", S["Liquid filters, such as raw, json or date:"].Value },
            { "LiquidDocumentation", S["see the Liquid documentation"].Value },
            { "AvailableFields", S["Fields ({0})"].Value },
            { "LastResult", S["Last result"].Value },
            { "LastResultHint", S["The value the activity that ran just before returned. Its type depends on that activity."].Value },
            { "LastResultFrom", S["{0}: {1}"].Value },
            { "CorrelationId", S["Correlation id"].Value },
            { "CorrelationIdHint", S["The id this instance is correlated with, for example a content item id."].Value },
            { "SourceInput", S["input"].Value },
            { "SourceOutput", S["output"].Value },
            { "SourceProperty", S["property"].Value },
            { "InsertExpression", S["Insert or copy {0}"].Value },
            { "ExpressionCopied", S["Copied {0}"].Value },
            { "ExpressionCopyFailed", S["The expression couldn't be copied."].Value },
            { "ValueCompletionDetail", S["{0}, from {1}"].Value },
            { "VariableInput", S["Input"].Value },
            { "VariableInputHint", S["Set by a workflow that runs this one as an activity, or by the input of the same name the workflow starts with."].Value },
            { "VariableOutput", S["Output"].Value },
            { "VariableOutputHint", S["Returned to a workflow that runs this one as an activity."].Value },
            { "NoValue", S["No value"].Value },
            { "AddVariable", S["Add a variable"].Value },
            { "DeleteVariable", S["Delete the variable {0}"].Value },
            { "NewVariable", S["new variable"].Value },
            { "NoDefaultForType", S["Variables of this type have no default value."].Value },
            { "NoDefault", S["No default value"].Value },
            { "True", S["True"].Value },
            { "False", S["False"].Value },
            { "InvalidDefaultValue", S["Enter a valid {0} value."].Value },
            { "VariableCompletionDetail", S["{0} variable"].Value },
            { "Outputs", S["Outputs"].Value },
            { "OutputsHint", S["Store the values this activity produces in workflow variables."].Value },
            { "OutputsHintReadOnly", S["The workflow variables that store the values this activity produces."].Value },
            { "NoVariablesToBind", S["Add variables in the Variables tab to store the values this activity produces."].Value },
            { "NotBound", S["Not stored"].Value },
            { "BoundVariableMissing", S["{0} isn't a declared variable."].Value },
            { "OutputTypeMismatch", S["A {0} value may not convert to {1} ({2}); the workflow then faults."].Value },
            { "IssuesTab", S["Issues"].Value },
            { "SelectActivityToEdit", S["Select an activity to edit it."].Value },
            { "MultipleSelected", S["{0} activities are selected."].Value },
            { "MissingActivityCannotBeEdited", S["This activity type isn't available, so it can't be edited. Enable its feature or delete it."].Value },
            { "LoadingForm", S["Loading…"].Value },
            { "FormLoadFailed", S["The form couldn't be loaded."].Value },
            { "Apply", S["Apply"].Value },
            { "Applying", S["Applying…"].Value },
            { "FormHasErrors", S["Fix the errors, then apply."].Value },
            { "ApplyFailed", S["The changes couldn't be applied. Try again."].Value },
            { "DiscardChangesTitle", S["Discard changes?"].Value },
            { "DiscardChangesMessage", S["The activity has errors, so its changes weren't applied. Discard them?"].Value },
            { "Discard", S["Discard"].Value },
            { "KeepEditing", S["Keep editing"].Value },
            { "TransitionsRemoved", S["{0} connection(s) were removed because their outcome no longer exists."].Value },
            { "NoIssues", S["No issues found."].Value },
            { "Error", S["Error"].Value },
            { "Warning", S["Warning"].Value },
            { "CollapsePanel", S["Collapse the panel"].Value },
            { "ExpandPanel", S["Expand the panel"].Value },
            { "ResizePanel", S["Resize the panel"].Value },
            { "ActivityDetails", S["Details"].Value },
            { "PinActivityPanel", S["Keep the activity panel open below the canvas"].Value },
            { "UnpinActivityPanel", S["Open the activity panel over the canvas only while an activity is selected"].Value },
            { "CloseActivityPanel", S["Close the activity panel"].Value },
            { "ResizeActivityPanel", S["Resize the activity panel"].Value },

            // Draft: autosave, publish and discard.
            { "Saved", S["All changes saved"].Value },
            { "Saving", S["Saving…"].Value },
            { "UnsavedChanges", S["Unsaved changes"].Value },
            { "SaveRetrying", S["Not saved. Retrying…"].Value },
            { "SaveFailed", S["Not saved."].Value },
            { "SaveConflict", S["Someone else changed this workflow."].Value },
            { "Retry", S["Retry"].Value },
            { "ResolveConflict", S["Resolve…"].Value },
            { "AnotherUser", S["another user"].Value },
            { "AlsoHereLabel", S["Also here:"].Value },
            { "AlsoHere", S["Also here: {0}"].Value },
            { "RemoteDraftChanged", S["{0} changed this workflow. Reload to see their changes."].Value },
            { "RemotePublished", S["{0} published this workflow."].Value },
            { "RemoteDraftDiscarded", S["{0} discarded the draft of this workflow."].Value },
            { "DraftLastEditedBy", S["Draft last edited by {0} at {1}."].Value },
            { "ConflictTitle", S["This workflow was changed"].Value },
            { "ConflictMessage", S["{0} changed this workflow at {1}, after this designer last saved it."].Value },
            { "ConflictMessageUnknown", S["The workflow was changed after this designer last saved it."].Value },
            { "ConflictReloadHint", S["Reload to get the latest version. Your unsaved changes are lost."].Value },
            { "ConflictOverwriteHint", S["Overwrite to save your layout and connections over theirs."].Value },
            { "Reload", S["Reload"].Value },
            { "Overwrite", S["Overwrite"].Value },
            { "Reloaded", S["The workflow was reloaded."].Value },
            { "ReloadFailed", S["The workflow couldn't be reloaded. Try again."].Value },
            { "Publish", S["Publish"].Value },
            { "PublishTitle", S["Publish the workflow?"].Value },
            { "PublishAnyway", S["Publish anyway"].Value },
            { "PublishWarningsMessage", S["The workflow has {0} warning(s):"].Value },
            { "RunningInstancesContinue", S["{0} running instance(s) keep running on the version they started on. New instances start on the new version."].Value },
            { "PublishBlockedTitle", S["The workflow can't be published"].Value },
            { "PublishBlockedMessage", S["Fix these {0} error(s) first:"].Value },
            { "Published", S["The workflow was published."].Value },
            { "PublishFailed", S["The workflow couldn't be published. Try again."].Value },
            { "SaveBeforePublishFailed", S["The changes couldn't be saved, so the workflow wasn't published."].Value },
            { "DiscardDraft", S["Discard draft"].Value },
            { "DiscardDraftTitle", S["Discard the draft?"].Value },
            { "DiscardDraftMessage", S["All changes since the workflow was last published are lost."].Value },
            { "DraftDiscarded", S["The draft was discarded."].Value },
            { "DiscardFailed", S["The draft couldn't be discarded. Try again."].Value },
            { "MoreActions", S["More actions"].Value },
            { "Instances", S["Instances"].Value },
            { "RunningInstanceCount", S["{0} running instance(s)"].Value },
            { "Export", S["Export"].Value },
            { "ExportHint", S["Exports the published workflow, without the draft."].Value },

            // Versions.
            { "Versions", S["Versions"].Value },
            { "VersionsHint", S["Each publish creates a version. View, compare or restore earlier versions."].Value },
            { "VersionsIntro", S["Each publish creates a version. Instances run on the version they started on, until they finish."].Value },
            { "VersionsLoadFailed", S["The versions couldn't be loaded."].Value },
            { "NoVersions", S["This workflow has no versions yet."].Value },
            { "Draft", S["Draft"].Value },
            { "VersionNumber", S["Version {0}"].Value },
            { "VersionPublished", S["Version {0} (published)"].Value },
            { "PublishedBadge", S["Published"].Value },
            { "PublishedVersion", S["The workflow was published as version {0}."].Value },
            { "PublishedVersionHint", S["The published version, which new instances start on."].Value },
            { "CreatedOnBy", S["{0} by {1}"].Value },
            { "ChangedOnBy", S["Changed {0} by {1}"].Value },
            { "InstanceCount", S["{0} instance(s)"].Value },
            { "VersionInstancesHint", S["The instances that run on this version. It isn't deleted while they exist."].Value },
            { "View", S["View"].Value },
            { "Compare", S["Compare"].Value },
            { "Restore", S["Restore"].Value },
            { "RestoreVersionTitle", S["Restore this version?"].Value },
            { "RestoreVersionMessage", S["Version {0} replaces the activities, connections and execution settings of the draft. The changes in the draft are lost."].Value },
            { "VersionRestored", S["Version {0} was copied into the draft. Publish it to make it the published version again."].Value },
            { "RestoreFailed", S["The version couldn't be restored."].Value },
            { "RunsOnVersion", S["Runs on version {0}"].Value },
            { "NotThePublishedVersion", S["not the published version"].Value },
            { "CompareWithPublished", S["Compare with the published version"].Value },
            { "OpenDesigner", S["Open the designer"].Value },

            // Comparing versions.
            { "Changes", S["Changes"].Value },
            { "ChangeAdded", S["Added"].Value },
            { "ChangeRemoved", S["Removed"].Value },
            { "ChangeChanged", S["Changed"].Value },
            { "ChangeMoved", S["Moved"].Value },
            { "ActivitiesAdded", S["Activities added"].Value },
            { "ActivitiesRemoved", S["Activities removed"].Value },
            { "ActivitiesChanged", S["Activities changed"].Value },
            { "ActivitiesMoved", S["Activities moved"].Value },
            { "ConnectionsAdded", S["Connections added"].Value },
            { "ConnectionsRemoved", S["Connections removed"].Value },
            { "SettingsChanged", S["Settings changed"].Value },
            { "NoChanges", S["The two definitions are the same."].Value },
            { "CompareLoadFailed", S["The comparison couldn't be loaded."].Value },

            // Instance viewer.
            { "SelectActivityToView", S["Select an activity to see its details."].Value },
            { "ActivityType", S["Type"].Value },
            { "InstanceStatus", S["This instance"].Value },
            { "WaitingOnActivity", S["Waiting on this activity"].Value },
            { "NotWaitingOnActivity", S["Not waiting on this activity"].Value },
            { "MissingActivity", S["This activity type isn't available. Enable its feature to run it."].Value },
            { "Blocking", S["Blocking"].Value },
            { "BlockingActivity", S["the instance waits on it"].Value },
            { "BlockingActivityHint", S["The workflow instance waits on this activity."].Value },
            { "BlockingLegend", S["The instance waits on these activities."].Value },
            { "ExecutedLegend", S["Activities and connections the instance ran."].Value },
            { "ExecutedTimes", S["ran {0} time(s)"].Value },
            { "FaultedActivity", S["faulted the instance"].Value },
            { "ScriptErrorActivity", S["a script failed and used its fallback value"].Value },
            { "ScriptErrorLegend", S["A script failed; the journal has the error."].Value },
            { "JournalScriptError", S["Script error"].Value },
            { "JournalTab", S["Journal"].Value },
            { "JournalTabHint", S["The activities this instance ran, in order. Select one to go to it."].Value },
            { "NoJournal", S["Nothing was recorded for this instance."].Value },
            { "JournalCompleted", S["Completed"].Value },
            { "JournalHalted", S["Waiting"].Value },
            { "JournalFaulted", S["Faulted"].Value },
            { "JournalResumed", S["Resumed"].Value },
            { "DurationMilliseconds", S["{0} ms"].Value },
            { "RetryFromHere", S["Retry from here"].Value },
            { "RetryTitle", S["Retry the instance?"].Value },
            { "RetryMessage", S["The instance runs again from {0}, with its current state."].Value },
            { "RetryFailed", S["The instance couldn't be retried."].Value },
            { "Retried", S["The instance ran again: {0}."].Value },

            // Canvas.
            { "Canvas", S["Workflow canvas"].Value },
            { "CanvasInstructions", S["Workflow canvas. Tab to an activity to select it; arrow keys move it, Delete removes it, Enter edits it, and the context menu key shows more actions."].Value },
            { "EmptyWorkflow", S["This workflow has no activities yet. Drag an activity from the toolbox to start."].Value },
            { "EmptyWorkflowReadOnly", S["This workflow has no activities."].Value },
            { "Activity", S["Activity"].Value },
            { "Start", S["Start"].Value },
            { "StartActivity", S["start activity"].Value },
            { "IssueCount", S["{0} issue(s)"].Value },
            { "ConnectOutcome", S["Outcome {0}: drag to an activity to connect it, or press Enter to choose one"].Value },
            { "ConnectOutcomeTo", S["Connect an outcome to…"].Value },
            { "ConnectOutcomeOf", S["Connect an outcome of {0}"].Value },
            { "Outcome", S["Outcome"].Value },
            { "Target", S["Target activity"].Value },
            { "Connect", S["Connect"].Value },
            { "ConnectionReplaced", S["The outcome {0} already had a connection; it was replaced."].Value },
            { "RemoveConnection", S["Remove connection {0} → {1}"].Value },
            { "DeleteConnection", S["Delete connection"].Value },
            { "Edit", S["Edit"].Value },
            { "SetAsStart", S["Set as start activity"].Value },
            { "UnsetStart", S["Unset start activity"].Value },
            { "Delete", S["Delete"].Value },
            { "DeleteSelected", S["Delete {0} activities"].Value },
            { "ActivityActions", S["Actions for {0}"].Value },
            { "ConnectionActions", S["Connection actions"].Value },
            { "DeletedActivity", S["Deleted 1 activity."].Value },
            { "DeletedActivities", S["Deleted {0} activities."].Value },
            { "DeletedConnection", S["Deleted the connection."].Value },
            { "Zoom", S["Zoom"].Value },
            { "ZoomIn", S["Zoom in"].Value },
            { "ZoomOut", S["Zoom out"].Value },
            { "ResetZoom", S["Reset zoom to 100%"].Value },
            { "FitToContent", S["Fit to content"].Value },
            { "CollapseActivities", S["Collapse the activities after it ({0})"].Value },
            { "ExpandActivities", S["Show the hidden activities after it ({0})"].Value },
            { "HiddenActivitiesAfter", S["{0} hidden activity(ies) after it"].Value },
            { "HiddenActivities", S["{0} activity(ies) hidden"].Value },
            { "ShowAll", S["Show all"].Value },
        };
    }
}
