//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Orchard.Tests.Localization {
    using System;
    using System.Reflection;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class PoSampleFiles {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal PoSampleFiles() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Orchard.Tests.Localization.PoSampleFiles", typeof(PoSampleFiles).GetTypeInfo().Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to #  translator-comments
        ///#. extracted-comments
        ///#: reference…
        ///#, flag
        ///
        ///#| msgctxt previous-context
        ///#| msgid previous-untranslated-string
        ///msgctxt &quot;Orchard.Localization&quot;
        ///msgid &quot;Unknown system error&quot;
        ///msgstr &quot;Error desconegut del sistema&quot;.
        /// </summary>
        internal static string EntryWithComments {
            get {
                return ResourceManager.GetString("EntryWithComments", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to msgctxt &quot;Orchard.Localization&quot;
        ///msgid &quot;Unknown system error&quot;
        ///msgstr &quot;Error desconegut del sistema&quot;.
        /// </summary>
        internal static string EntryWithContext {
            get {
                return ResourceManager.GetString("EntryWithContext", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to msgid &quot;Line:\t\&quot;{0}\&quot;\n&quot;
        ///msgstr &quot;Line:\t\&quot;{0}\&quot;\n&quot;.
        /// </summary>
        internal static string EntryWithEscapedCharacters {
            get {
                return ResourceManager.GetString("EntryWithEscapedCharacters", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to msgid &quot;&quot;
        ///&quot;Here is an example of how one might continue a very long string\n&quot;
        ///&quot;for the common case the string represents multi-line output.&quot;
        ///msgstr &quot;&quot;
        ///&quot;Here is an example of how one might continue a very long translation\n&quot;
        ///&quot;for the common case the string represents multi-line output.&quot;.
        /// </summary>
        internal static string EntryWithMultilineText {
            get {
                return ResourceManager.GetString("EntryWithMultilineText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &quot;msgid &quot;Unknown system error&quot;
        ///&quot;msgstr &quot;&quot;.
        /// </summary>
        internal static string EntryWithoutTranslation {
            get {
                return ResourceManager.GetString("EntryWithoutTranslation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to msgid &quot;book&quot;
        ///msgid_plural &quot;books&quot;
        ///msgstr[0] &quot;kniha&quot;
        ///msgstr[1] &quot;knihy&quot;
        ///msgstr[2] &quot;knih&quot;.
        /// </summary>
        internal static string EntryWithPlural {
            get {
                return ResourceManager.GetString("EntryWithPlural", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to msgid &quot;Foo \&quot;{0}\&quot;&quot;
        ///msgstr &quot;Foo \&quot;{0}\&quot;&quot;.
        /// </summary>
        internal static string EntryWithQuotes {
            get {
                return ResourceManager.GetString("EntryWithQuotes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to #. &quot;File {0} does not exist&quot;
        ///msgctxt &quot;Orchard.FileSystems.Media.FileSystemStorageProvider&quot;
        ///msgid &quot;File {0} does not exist&quot;
        ///msgstr &quot;Soubor {0} neexistuje&quot;
        ///
        ///#. &quot;Directory {0} does not exist&quot;
        ///msgctxt &quot;Orchard.FileSystems.Media.Directory&quot;
        ///msgid &quot;Directory {0} does not exist&quot;
        ///msgstr &quot;Složka {0} neexistuje&quot;.
        /// </summary>
        internal static string MultipleEntries {
            get {
                return ResourceManager.GetString("MultipleEntries", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to msgid &quot;&quot;
        ///msgstr &quot;&quot;
        ///&quot;POT-Creation-Date: 2016-06-22 17:06+0200\n&quot;
        ///&quot;PO-Revision-Date: 2016-08-01 11:57+0200\n&quot;
        ///&quot;X-Poedit-Basepath: ../../..\n&quot;.
        /// </summary>
        internal static string PoeditHeader {
            get {
                return ResourceManager.GetString("PoeditHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to msgid &quot;Unknown system error&quot;
        ///msgstr &quot;Error desconegut del sistema&quot;.
        /// </summary>
        internal static string SimpleEntry {
            get {
                return ResourceManager.GetString("SimpleEntry", resourceCulture);
            }
        }
    }
}
