<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <!-- NuGet properties-->
    <Title>OrchardCore SignalR Core</Title>
    <Description>$(OCFrameworkDescription)

    Shared abstractions for the OrchardCore SignalR module, allowing other modules to declare SignalR hubs without referencing the module directly.</Description>
    <PackageTags>$(PackageTags) OrchardCoreFramework SignalR</PackageTags>
  </PropertyGroup>

</Project>
