using System.Collections.Immutable;
using System.Security.Cryptography;
using System.Text;
using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.CSharp.Syntax;
using Microsoft.CodeAnalysis.Text;

#nullable enable

namespace OrchardCore.DisplayManagement.SourceGenerators;

[Generator]
public class ShapeFactoryGenerator : IIncrementalGenerator
{
    private const string ShapeFactoryExtensionsFullName = "OrchardCore.DisplayManagement.ShapeFactoryExtensions";
    private const string IShapeFullName = "OrchardCore.DisplayManagement.IShape";

    public void Initialize(IncrementalGeneratorInitializationContext context)
    {
        var shapeTypes = context.SyntaxProvider
            .CreateSyntaxProvider(
                predicate: static (node, _) => IsCreateAsyncInvocation(node),
                transform: static (context, ct) => GetShapeType(context, ct))
            .Where(static type => type is not null);

        context.RegisterSourceOutput(
            shapeTypes.Collect(),
            static (spc, types) => Execute(types!, spc));
    }

    private static bool IsCreateAsyncInvocation(SyntaxNode node)
        => node is InvocationExpressionSyntax;

    private static INamedTypeSymbol? GetShapeType(GeneratorSyntaxContext context, CancellationToken cancellationToken)
    {
        var invocation = (InvocationExpressionSyntax)context.Node;
        var symbolInfo = context.SemanticModel.GetSymbolInfo(invocation, cancellationToken);

        if (symbolInfo.Symbol is not IMethodSymbol methodSymbol)
        {
            return null;
        }

        var targetMethod = methodSymbol.ReducedFrom ?? methodSymbol.OriginalDefinition;

        if (targetMethod.Name != "CreateAsync" ||
            targetMethod.ContainingType?.ToDisplayString() != ShapeFactoryExtensionsFullName ||
            !methodSymbol.IsGenericMethod ||
            methodSymbol.TypeArguments.Length == 0 ||
            !UsesStronglyTypedShapeFactory(targetMethod))
        {
            return null;
        }

        if (methodSymbol.TypeArguments[0] is not INamedTypeSymbol typeSymbol ||
            typeSymbol.TypeKind != TypeKind.Class ||
            typeSymbol.IsAbstract ||
            ImplementsIShape(typeSymbol))
        {
            return null;
        }

        if (!HasAccessibleParameterlessConstructor(typeSymbol))
        {
            return null;
        }

        return typeSymbol;
    }

    private static bool UsesStronglyTypedShapeFactory(IMethodSymbol methodSymbol)
    {
        var tModel = methodSymbol.TypeParameters[0];

        return methodSymbol.Parameters.Any(parameter =>
            parameter.Type is INamedTypeSymbol namedType &&
            namedType.ContainingNamespace?.ToDisplayString() == "System" &&
            (namedType.Name == "Action" || namedType.Name == "Func") &&
            namedType.TypeArguments.Length > 0 &&
            SymbolEqualityComparer.Default.Equals(namedType.TypeArguments[0], tModel));
    }

    private static bool ImplementsIShape(INamedTypeSymbol typeSymbol)
        => typeSymbol.AllInterfaces.Any(i => i.ToDisplayString() == IShapeFullName);

    private static bool HasAccessibleParameterlessConstructor(INamedTypeSymbol typeSymbol)
    {
        if (typeSymbol.InstanceConstructors.Length == 0)
        {
            return true;
        }

        return typeSymbol.InstanceConstructors.Any(ctor =>
            ctor.Parameters.Length == 0 &&
            ctor.DeclaredAccessibility is Accessibility.Public or Accessibility.Internal or Accessibility.Protected or Accessibility.ProtectedOrInternal);
    }

    private static void Execute(ImmutableArray<INamedTypeSymbol> types, SourceProductionContext context)
    {
        if (types.IsDefaultOrEmpty)
        {
            return;
        }

        var distinctTypes = types.Distinct<INamedTypeSymbol>(SymbolEqualityComparer.Default).ToArray();
        if (distinctTypes.Length == 0)
        {
            return;
        }

        var sb = new StringBuilder();

        sb.AppendLine("// <auto-generated />");
        sb.AppendLine("#nullable enable");
        sb.AppendLine();
        sb.AppendLine("namespace OrchardCore.DisplayManagement.Generated");
        sb.AppendLine("{");
        sb.AppendLine("    internal static class ShapeFactoryGeneratedRegistration");
        sb.AppendLine("    {");
        sb.AppendLine("        [global::System.Runtime.CompilerServices.ModuleInitializer]");
        sb.AppendLine("        internal static void Register()");
        sb.AppendLine("        {");

        for (var i = 0; i < distinctTypes.Length; i++)
        {
            var typeName = distinctTypes[i].ToDisplayString(SymbolDisplayFormat.FullyQualifiedFormat);
            sb.AppendLine($"            global::OrchardCore.DisplayManagement.GeneratedShapeTypeRegistry.Register(typeof({typeName}), typeof({GetGeneratedTypeName(distinctTypes[i])}));");
        }

        sb.AppendLine("        }");
        sb.AppendLine("    }");
        sb.AppendLine();

        for (var i = 0; i < distinctTypes.Length; i++)
        {
            GenerateShapeType(sb, distinctTypes[i]);
        }

        sb.AppendLine("}");

        context.AddSource("ShapeFactoryGenerator.g.cs", SourceText.From(sb.ToString(), Encoding.UTF8));
    }

    private static void GenerateShapeType(StringBuilder sb, INamedTypeSymbol typeSymbol)
    {
        var baseTypeName = typeSymbol.ToDisplayString(SymbolDisplayFormat.FullyQualifiedFormat);
        var generatedTypeName = GetGeneratedTypeName(typeSymbol);

        sb.AppendLine($"    file sealed class {generatedTypeName} : {baseTypeName}, global::OrchardCore.DisplayManagement.IShape, global::OrchardCore.DisplayManagement.IPositioned");
        sb.AppendLine("    {");
        sb.AppendLine("        private readonly global::OrchardCore.DisplayManagement.Views.ShapeViewModel _shape = new();");
        sb.AppendLine();
        sb.AppendLine("        public global::OrchardCore.DisplayManagement.Shapes.ShapeMetadata Metadata => _shape.Metadata;");
        sb.AppendLine();
        sb.AppendLine("        public string Position");
        sb.AppendLine("        {");
        sb.AppendLine("            get => _shape.Position;");
        sb.AppendLine("            set => _shape.Position = value;");
        sb.AppendLine("        }");
        sb.AppendLine();
        sb.AppendLine("        public string Id");
        sb.AppendLine("        {");
        sb.AppendLine("            get => _shape.Id;");
        sb.AppendLine("            set => _shape.Id = value;");
        sb.AppendLine("        }");
        sb.AppendLine();
        sb.AppendLine("        public string TagName");
        sb.AppendLine("        {");
        sb.AppendLine("            get => _shape.TagName;");
        sb.AppendLine("            set => _shape.TagName = value;");
        sb.AppendLine("        }");
        sb.AppendLine();
        sb.AppendLine("        public global::System.Collections.Generic.IList<string> Classes => _shape.Classes;");
        sb.AppendLine();
        sb.AppendLine("        public global::System.Collections.Generic.IDictionary<string, string> Attributes => _shape.Attributes;");
        sb.AppendLine();
        sb.AppendLine("        public global::System.Collections.Generic.IDictionary<string, object> Properties => _shape.Properties;");
        sb.AppendLine();
        sb.AppendLine("        public global::System.Collections.Generic.IReadOnlyList<global::OrchardCore.DisplayManagement.IPositioned> Items => _shape.Items;");
        sb.AppendLine();
        sb.AppendLine("        public global::System.Threading.Tasks.ValueTask<global::OrchardCore.DisplayManagement.IShape> AddAsync(object item, string position)");
        sb.AppendLine("            => _shape.AddAsync(item, position);");
        sb.AppendLine("    }");
        sb.AppendLine();
    }

    private static string GetGeneratedTypeName(INamedTypeSymbol typeSymbol)
    {
        var typeName = typeSymbol.ToDisplayString(SymbolDisplayFormat.FullyQualifiedFormat);
        using var sha256 = SHA256.Create();
        var hash = sha256.ComputeHash(Encoding.UTF8.GetBytes(typeName));

        return $"GeneratedShape_{BitConverter.ToString(hash).Replace("-", "")}";
    }
}
