name: Set Up .NET
description: Centralized actions/setup-dotnet for easier updates.

runs:
  using: composite
  steps:
    - name: Set Up .NET
      uses: actions/setup-dotnet@baa11fbfe1d6520db94683bd5c7a3818018e4309 # v5.1.0
      with:
        dotnet-version: | 
          10.0.x
