name: Set Up .NET
description: Centralized actions/setup-dotnet for easier updates.

runs:
  using: composite
  steps:
    - name: Set Up .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: | 
          8.0.x
          9.0.x