name: Set Up .NET
description: Centralized actions/setup-dotnet for easier updates.

runs:
  using: composite
  steps:
    - name: Set Up .NET
      uses: actions/setup-dotnet@a98b56852c35b8e3190ac28c8c2271da59106c68 # v6.0.0
