name: Functional Tests - All Databases

on:
  # Manual trigger.
  workflow_dispatch:
  pull_request_review:
    types: [submitted]
  # Run it on main and release pushes too, in case we merge from a branch that's not up-to-date with the target branch
  # and breaks something after merge (or if we push to main).
  push:
    paths-ignore:
      - '**/*.md'
      - 'mkdocs.yml'
      - 'src/docs/**/*'
    branches: [ main, release/** ]

env:
  DOTNET_SKIP_FIRST_TIME_EXPERIENCE: true
  DOTNET_CLI_TELEMETRY_OPTOUT: true

jobs:
  test_functional_mvc:
    name: Functional Tests - MVC
    # These conditions are needed because the workflow triggers on individual PR comments too, see
    # https://github.com/orgs/community/discussions/124396.
    # They either need to be repeated for each job, or we need to use a separate job (i.e. VM to run the condition) that
    # triggers the others.
    if: github.event_name == 'workflow_dispatch' ||
        github.event_name == 'push' ||
        github.event.review.state == 'APPROVED' ||
        github.event.review.state == 'CHANGES_REQUESTED'
    runs-on: ubuntu-24.04
    steps:
    - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
    - uses: ./.github/actions/setup-dotnet
    - uses: actions/setup-node@53b83947a5a98c8d113130e565377fae1a50d02f # v6.3.0
      with:
        node-version: "20"
        package-manager-cache: false
    - name: Cache Playwright Browsers
      uses: actions/cache@5a3ec84eff668545956fd18022155c47e93e2684 # v4.2.3
      with:
        path: ~/.cache/ms-playwright
        key: playwright-${{ hashFiles('test/OrchardCore.Tests.Playwright/package.json') }}
    - name: Install Playwright Browsers
      run: |
        npm install -g corepack
        corepack enable
        yarn install
        yarn workspace @orchardcore/tests-playwright exec playwright install --with-deps chromium
    - name: Functional Tests
      run: |
        yarn workspace @orchardcore/tests-playwright test:mvc
    - uses: actions/upload-artifact@bbbca2ddaa5d8feaa63e36b76fdaad77386f024f # v7.0.0
      if: failure()
      with:
        name: functional-mvc-failure
        path: |
          test/OrchardCore.Tests.Playwright/playwright-report/
          test/OrchardCore.Tests.Playwright/test-results/
        retention-days: 3

  test_functional_cms_sqlite:
    name: Functional Tests - CMS Sqlite
    if: github.event_name == 'workflow_dispatch' ||
        github.event_name == 'push' ||
        github.event.review.state == 'APPROVED' ||
        github.event.review.state == 'CHANGES_REQUESTED'
    runs-on: ubuntu-24.04
    env:
      OrchardCore__OrchardCore_YesSql__EnableThreadSafetyChecks: true
    steps:
    - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
    - uses: ./.github/actions/setup-dotnet
    - uses: actions/setup-node@53b83947a5a98c8d113130e565377fae1a50d02f # v6.3.0
      with:
        node-version: "20"
        package-manager-cache: false
    - name: Cache Playwright Browsers
      uses: actions/cache@5a3ec84eff668545956fd18022155c47e93e2684 # v4.2.3
      with:
        path: ~/.cache/ms-playwright
        key: playwright-${{ hashFiles('test/OrchardCore.Tests.Playwright/package.json') }}
    - name: Install Playwright Browsers
      run: |
        npm install -g corepack
        corepack enable
        yarn install
        yarn workspace @orchardcore/tests-playwright exec playwright install --with-deps chromium
    - name: Functional Tests
      run: |
        yarn workspace @orchardcore/tests-playwright test:cms
    - uses: actions/upload-artifact@bbbca2ddaa5d8feaa63e36b76fdaad77386f024f # v7.0.0
      if: failure()
      with:
        name: functional-cms-sqlite-failure
        path: |
          test/OrchardCore.Tests.Playwright/playwright-report/
          test/OrchardCore.Tests.Playwright/test-results/
          src/OrchardCore.Cms.Web/App_Data_Tests/logs
        retention-days: 3

  test_functional_cms_postgresql:
    name: Functional Tests - CMS Postgres
    if: github.event_name == 'workflow_dispatch' ||
        github.event_name == 'push' ||
        github.event.review.state == 'APPROVED' ||
        github.event.review.state == 'CHANGES_REQUESTED'
    runs-on: ubuntu-24.04
    services:
      postgres:
        image: postgres:11
        ports:
          - 5432:5432
        env:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: admin
          POSTGRES_DB: app
        # Set health checks to wait until postgres has started
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
    env:
      OrchardCore__ConnectionString: "User ID=postgres;Password=admin;Host=localhost;Port=5432;Database=app;"
      OrchardCore__DatabaseProvider: "Postgres"
      OrchardCore__OrchardCore_YesSql__EnableThreadSafetyChecks: true
    steps:
    - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
    - uses: ./.github/actions/setup-dotnet
    - uses: actions/setup-node@53b83947a5a98c8d113130e565377fae1a50d02f # v6.3.0
      with:
        node-version: "20"
        package-manager-cache: false
    - name: Cache Playwright Browsers
      uses: actions/cache@5a3ec84eff668545956fd18022155c47e93e2684 # v4.2.3
      with:
        path: ~/.cache/ms-playwright
        key: playwright-${{ hashFiles('test/OrchardCore.Tests.Playwright/package.json') }}
    - name: Install Playwright Browsers
      run: |
        npm install -g corepack
        corepack enable
        yarn install
        yarn workspace @orchardcore/tests-playwright exec playwright install --with-deps chromium
    - name: Functional Tests
      run: |
        yarn workspace @orchardcore/tests-playwright test:cms
    - uses: actions/upload-artifact@bbbca2ddaa5d8feaa63e36b76fdaad77386f024f # v7.0.0
      if: failure()
      with:
        name: functional-cms-postgresql-failure
        path: |
          test/OrchardCore.Tests.Playwright/playwright-report/
          test/OrchardCore.Tests.Playwright/test-results/
          src/OrchardCore.Cms.Web/App_Data_Tests/logs
        retention-days: 3

  test_functional_cms_mysql:
    name: Functional Tests - CMS MySql
    if: github.event_name == 'workflow_dispatch' ||
        github.event_name == 'push' ||
        github.event.review.state == 'APPROVED' ||
        github.event.review.state == 'CHANGES_REQUESTED'
    runs-on: ubuntu-24.04
    services:
      mysql:
        image: mysql:8
        ports:
          - 3306:3306
        env:
          MYSQL_DATABASE: test
          MYSQL_ROOT_PASSWORD: test123
        options: --health-cmd="mysqladmin ping" --health-interval=10s --health-timeout=5s --health-retries=3
    env:
      OrchardCore__ConnectionString: "server=localhost;uid=root;pwd=test123;database=test"
      OrchardCore__DatabaseProvider: "MySql"
      OrchardCore__OrchardCore_YesSql__EnableThreadSafetyChecks: true
    steps:
    - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
    - uses: ./.github/actions/setup-dotnet
    - uses: actions/setup-node@53b83947a5a98c8d113130e565377fae1a50d02f # v6.3.0
      with:
        node-version: "20"
        package-manager-cache: false
    - name: Cache Playwright Browsers
      uses: actions/cache@5a3ec84eff668545956fd18022155c47e93e2684 # v4.2.3
      with:
        path: ~/.cache/ms-playwright
        key: playwright-${{ hashFiles('test/OrchardCore.Tests.Playwright/package.json') }}
    - name: Install Playwright Browsers
      run: |
        npm install -g corepack
        corepack enable
        yarn install
        yarn workspace @orchardcore/tests-playwright exec playwright install --with-deps chromium
    - name: Functional Tests
      run: |
        yarn workspace @orchardcore/tests-playwright test:cms
    - uses: actions/upload-artifact@bbbca2ddaa5d8feaa63e36b76fdaad77386f024f # v7.0.0
      if: failure()
      with:
        name: functional-cms-mysql-failure
        path: |
          test/OrchardCore.Tests.Playwright/playwright-report/
          test/OrchardCore.Tests.Playwright/test-results/
          src/OrchardCore.Cms.Web/App_Data_Tests/logs
        retention-days: 3

  test_functional_cms_mssql:
    name: Functional Tests - CMS SqlServer 2019
    if: github.event_name == 'workflow_dispatch' ||
        github.event_name == 'push' ||
        github.event.review.state == 'APPROVED' ||
        github.event.review.state == 'CHANGES_REQUESTED'
    runs-on: ubuntu-24.04
    services:
      mssql:
        image: mcr.microsoft.com/mssql/server:2019-latest
        ports:
          - 1433:1433
        env:
          ACCEPT_EULA: Y
          MSSQL_SA_PASSWORD: Password12!
    env:
      OrchardCore__ConnectionString: "Server=localhost;Database=tempdb;User Id=sa;Password=Password12!;Encrypt=False"
      OrchardCore__DatabaseProvider: "SqlConnection"
      OrchardCore__OrchardCore_YesSql__EnableThreadSafetyChecks: true
    steps:
    - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
    - uses: ./.github/actions/setup-dotnet
    - uses: actions/setup-node@53b83947a5a98c8d113130e565377fae1a50d02f # v6.3.0
      with:
        node-version: "20"
        package-manager-cache: false
    - name: Cache Playwright Browsers
      uses: actions/cache@5a3ec84eff668545956fd18022155c47e93e2684 # v4.2.3
      with:
        path: ~/.cache/ms-playwright
        key: playwright-${{ hashFiles('test/OrchardCore.Tests.Playwright/package.json') }}
    - name: Install Playwright Browsers
      run: |
        npm install -g corepack
        corepack enable
        yarn install
        yarn workspace @orchardcore/tests-playwright exec playwright install --with-deps chromium
    - name: Functional Tests
      run: |
        yarn workspace @orchardcore/tests-playwright test:cms
    - uses: actions/upload-artifact@bbbca2ddaa5d8feaa63e36b76fdaad77386f024f # v7.0.0
      if: failure()
      with:
        name: functional-cms-mssql-failure
        path: |
          test/OrchardCore.Tests.Playwright/playwright-report/
          test/OrchardCore.Tests.Playwright/test-results/
          src/OrchardCore.Cms.Web/App_Data_Tests/logs
        retention-days: 3
